# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: yuqiang.gu@dhbw-stuttgart.de
author_name: Yuqiang Gu
has_binder: true
has_settings: false
kind: server
labextension_name: GenAIgrader
project_short_description: A JupyterLab extension for using nbgrader with GenAI.
python_name: GenAIgrader
repository: https://github.com/databrix-org/GenAIgrader
test: true

